//Error status codes for error message
const errorResponse = {
    //General Error
    DB_ERROR: "110-DB Error",
    INVALID_PAGE_NO: "1401-Invalid page number",
    INVALID_PAGE_SIZE: "1402-Invalid page size",
    API_NOT_FOUND: "1002-API not found ",
    AUTHENTICATION_REQUIRED: "1009-Authentication required",
    //User 
    USER_REGISTRATION_USER_NAME_ERROR: "1010-Name Required",
    OLD_PASSWORD_REQUIRED: "22401-Old Password Required",
    NEW_PASSWORD_REQUIRED: "22402-New Password Required",
    INVALID_PASSWORD: "22404-Invalid  password",
    NAME_REQUIRED: "21101-Name Required",
    EMAIL_REQURIED: "21102-Email Required",
    INCORRECT_MAIL_FORMAT: "21103-Incorrect mail format",
    PASSWORD_REQUIRED: "21104-password Required",
    INCORRECT_PASSWORD_FORMAT: "21105-Incorrect password format",
    DATE_OF_BIRT_REQUIRED: "21107-Date of Birth Required",
    LOCATION_REQUIRED: "21106-Location Required",
    SKILL_REQUIRED: "21108-skill Required",
    EXPERIENCE_REQUIRE: "21109-Experience Required",
    CATEGORY_REQUIRED: "21110-Category Required",
    EMAIL_ALREADY_EXIST: "21111-Email already exist",
    USER_DELETED: "21114-User deleted",
    USER_UNPUBLISHED: "21115-User unpublished",
    PASSWORD_ALREADY_CHANGED: "21116-Password already changed",
    INVALID_INTERESTED_CATEGORIES: "21117-Invalid interested categories",
    INVALID_PREFECTURE: "21118-Invalid prefecture",
    EMAIL_NOT_VERIFIED: "21119-Email not verified",
    FIRSTNAME_INVALID: "21120-Invalid firstName",
    LOCATION_INVALID: "21121-Invalid Location",
    DOB_INVALID: "21122-Invalid DOB",
    SKILL_INVALID: "21122-Invalid Skill",
    EXPERIENCE_INVALID: "21122-Invalid Experience",
    INTERESTED_JOB_CATEGORIES_INVALID: "21123-Invalid InterestedJobCategory",
    USER_IS_ALREADY_ACTIVE: "21401-User is already activated",
    INVALID_TELEPHONE_NUMBER:"21402-Invalid Telephone Number",
    PREFECTURE_REQUIRED:"21403-Prefecture Required",
    INVALID_DESIRED_OCCUPATION:"21404-Invalid Desired Occupation",
    INVALID_RESUME:"21405-Invalid Resume",
    TELEPHONE_NUMBER_REQUIRED:"21406-Invalid Telephone Number",
    DESIRED_OCCUPATION_REQUIRED:"21407-Desired Occupation Required",
    MIDDLE_NAME_INVALID:"21408-Invalid Middle Name",
    LAST_NAME_REQUIRED:"21409-Last Name Required",
    LAST_NAME_INVALID:"21410-Invalid Last Name",
    CITY_REQUIRED:"21411-City Required",
    CITY_INVALID:"21412-Invalid City",
    INVALID_APARTMENT_NAME:"21413-Invalid Apartment Name",
    //query params
    INVALID_SOURCE: "Source must be 0,1 or 2",
    //User email verification
    TOKEN_REQUIRED: "21301-Token Required",
    TOKEN_INVALID: "22201-Invalid token",
    TOKEN_EXPIRED: "22202-Token expired",
    TOKEN_EXPIRED_RESEND: "21304-Token Expired resending the token ",
    //LOGIN
    USERNAME_REQUIRED: "21201-Username Required.",
    LOGIN_PASSWORD_REQUIRED: "21202-Password Required.",
    USERNAME_AND_PASSWORD_MISMATCH: "21203-Username and password does not match.",
    USER_NOT_FOUND: "21204-User not found",
    LOGIN_INVALID_EMAIL: "21112-Invalid email",
    LOGIN_INVALID_PASSWORD:"21113-Invalid password",
    //FORGOT_PASSWORD
    FORGOT_PASSWORD_EMAIL_REQUIRED:"22101-Email Required",
    FORGOT_PASSWORD_EMAIL_NOT_FOUND:"22102-Email not Found.",	
    //Job List
    INVALID_INDUSTRY: "26101-Invalid industry",
    INVALID_CREATED_DATE: "26102-Invalide created date",
    INVALID_JOB_ID: "26103-Invalid job id",
    INVALID_SALARIES: "26104-Invalid min and max salary",
    INVALID_MIN_SALARY: "26105-Invalid min salary",
    INVALID_MAX_SALARY: "26106-Invalid max salary",
    USER_JOB_APPLIED: "26301-User already applied for a job",
    //Inquiry Form
    Error_name_reqiured: "27101-Name Required",
    Error_name_string: "27102-Name should be string",
    Error_name_Empty: "27103-Name text should not be empty",
    Error_question_inquiry_required: "27104-Question Required",
    Error_question_inquiry_string: "27105-Question should be string",
    Error_question_inquiry_Empty: "27106-Question text should not be empty",
    Error_name_Max_Exceeded: "27107-Name max size exceeded",
    Error_question_Max_Exceeded: "27108-Question max size exceeded",
    Error_description_Max_Exceeded:"27109-Description max size exceeded",
    Error_description_Empty:"27110-Description should not be empty",
    //career_counselling
    Error_question_answer_count: "23105-number of questions and answers should be same",
    Error_question_required: "23101-Array of questions is required",
    Error_answer_required: "23103-Array of answers Required",
    Error_question_length: "23104-Length of question Text should be  less than 100 characters",
    Error_answer_length: "23106-Length of answer Text should be  less than 100 characters",
    Error_answer_string: "23107-answer should be string",
    Error_question_string: "23108-question should be string",
    Error_answer_Empty: "23109-answer text should not be empty",
    Error_question_Empty: "23110-question text should not be empty",
    CAREER_COUNSELING_USER_APPLIED: "23701-Career counseling applied by user",
    //common_error code
    Error_invalid_email_format: "21103-Incorrect mail format",
    Error_email_required: "21102-Email Required",
    EMAIL_FAILED: "2003-Mail sending Failed",
    //Company query params
    INVALID_INDUSTRY_ID: "Must be a integer number",
    FILE_REQUIRED: "2004-Invalid file",

}

module.exports = errorResponse;